server:
  port: 8080

spring:
  application:
    name: linguacards-backend

  datasource:
    url: jdbc:mysql://localhost:3306/linguacards?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: lingua
    password: lingua123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

app:
  cors:
    allowed-origin: http://localhost:4200
  security:
    require-auth-for-api: true
    jwt:
      # 32+ символа, просто строка (не base64)
      secret: "change-me-please-change-me-please-1234"
      issuer: linguacards
      ttl-seconds: 3600