server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: linguacards-v2

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/linguacards}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  flyway:
    locations: classpath:db/migration/{vendor}

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate

app:
  security:
    jwt:
      issuer: ${JWT_ISSUER:http://localhost:8080}
      secret: ${JWT_SECRET}
      expiration-minutes: ${JWT_EXPIRATION_MINUTES:60}
