server:
  port: 8080

spring:
  application:
    name: linguacards-v2

  profiles:
    # Для учебного проекта удобно, чтобы IntelliJ запускал сразу local
    default: local

  jpa:
    open-in-view: false